const translations = {
	en: {
	home: "Home",
	language: "Language",
	play: "Play",
	leaderboard: "Leaderboard",
	stats: "Stats",
	profile: "Profile",
	login: "Log in",
	register: "Sign up",
	login42: "Log in with 42",
	signup42: "Sign up with 42",
	logout: "Log out",
	localMatch: "Play local",
	onlineMatch: "Play online",
	botMatch: "Play against bot",
	tournament: "Tournament",
	back: "Back",
	pause: "Pause",
	resume: "Resume",
	restart: "Restart",
	sendFriend: "Send Friend Request",
	quit: "Quit",
	quitMessage: "Are you sure you want to quit?",
	footer: "Developed by fracerba, ncortigi, everonel, lgaibazz",
	email: "Email address",
	username: "Username",
	password: "Password",
	oldPassword: "Current Password",
	newPassword: "New Password",
	submit: "Submit",
	emailHelp: "Please enter a valid email address",
	userHelp: "Max 10 alphanumeric characters",
	passHelp: "Password should have at least 8 characters, one capital letter, one number",
	oldPasswordHelp: "Enter your current password",
	newPasswordHelp: "Enter your new password or leave it blank",
	emailError: "Invalid email",
	passError: "Wrong password",
	oldPassError: "Wrong current password",
	player: "Player",
	games: "Games",
	wins: "Wins",
	losses: "Losses",
	winrate: "Win rate",
	tournamentWon: "Tournaments Won",
	uploadImage: "Upload Image",
	info: "Info",
	edit: "Edit",
	save: "Save",
	recentGames: "Recent Games",
	viewStats: "Full Stats",
	friends: "Friends",
	friendRequests: "Friend Requests",
	accept: "Accept",
	reject: "Reject",
	sentRequests: "Sent Requests",
	generalStats: "Player Stats",
	modeResults: "Mode Results",
	localGames: "Local Games",
	botGames: "Games against bot",
	tournamentGames: "Tournament Matches",
	win: "Win",
	loss: "Loss",
	local: "Local",
	online: "Online",
	bot: "Bot",
	ingame: "In game",
	comingSoon: "Coming soon...",
	createTournament: "Create tournament",
	name: "Tournament name",
	tournamentError: "Can't be blank",
	tournamentPlayers: "Number of players",
	selectError: "Select a number",
	creator: "Creator",
	kick: "Kick",
	startTournament: "Start tournament",
	searchPlayers: "Search players",
	search: "Search",
	viewProfile: "View Profile",
	leaderboardEmpty: "No leaderboard available",
	noMatches: "No matches played",
	noFriends: "No friends yet",
	noRequests: "No incoming friend requests",
	noSentRequests: "No sent friend requests",
	noPlayers: "No players found",
	yes: "Yes",
	no: "No",
	tris: "Tic-Tac-Toe",
	playPong: "Play Pong",
	playTris: "Play Tic-Tac-Toe",
	loginSecond: "Log in second player",
	id: "Unique ID",
	editProfile: "Edit Profile",
	errorModalEmail: "Email error",
	errorModalPass: "Password error",
	emailInUse: "This email is already taken. Please choose another one.",
	points: "Points",
	firstRound: "First Round",
	secondRound: "Second Round",
	thirdRound: "Third Round",
	fourthRound: "Fourth Round",
	startNextMatch: "Start Next Match",
	startNextRound: "Start Next Round",
	pointDiff: "Point Difference",
	passModal: "Password is not valid: ",
	},
	it: {
	home: "Homepage",
	language: "Lingua",
	play: "Gioca",
	leaderboard: "Classifica",
	stats: "Statistiche",
	profile: "Profilo",
	login: "Accedi",
	register: "Iscriviti",
	login42: "Accedi con 42",
	signup42: "Iscriviti con 42",
	logout: "Esci",
	localMatch: "Gioca in locale",
	onlineMatch: "Gioca online",
	botMatch: "Gioca contro il bot",
	tournament: "Torneo",
	back: "Indietro",
	pause: "Pausa",
	resume: "Riprendi",
	restart: "Ricomincia",
	sendFriend: "Invia Richiesta di Amicizia",
	quit: "Esci",
	quitMessage: "Sei sicuro di voler uscire?",
	footer: "Sviluppato da fracerba, ncortigi, everonel, lgaibazz",
	email: "Indirizzo email",
	username: "Nome utente",
	password: "Password",
	oldPassword: "Password attuale",
	newPassword: "Nuova password",
	submit: "Conferma",
	emailHelp: "Inserisci un indirizzo email valido", 
	userHelp: "Massimo 10 caratteri alfanumerici",
	passHelp: "La password deve contenere almeno 8 caratteri, una lettera maiuscola e un numero",
	oldPasswordHelp: "Inserisci la tua password attuale",
	newPasswordHelp: "Inserisci la tua nuova password o lasciala vuota",
	emailError: "Email non valida",
	passError: "Password errata",
	oldPassError: "Password attuale errata",
	player: "Giocatore",
	games: "Partite",
	wins: "Vittorie",
	losses: "Sconfitte",
	winrate: "Percentuale di vittorie",
	tournamentWon: "Tornei vinti",
	uploadImage: "Carica immagine",
	info: "Informazioni",
	edit: "Modifica",
	save: "Salva",
	recentGames: "Partite recenti",
	viewStats: "Statistiche complete",
	friends: "Amici",
	friendRequests: "Richieste di amicizia",
	accept: "Accetta",
	reject: "Rifiuta",
	sentRequests: "Richieste inviate",
	generalStats: "Statistiche generali",
	modeResults: "Risultati per modalità",
	localGames: "Partite in locale",
	botGames: "Partite contro il bot",
	tournamentGames: "Partite di torneo",
	win: "Vittoria",
	loss: "Sconfitta",
	local: "Locale",
	online: "Online",
	bot: "Bot",
	ingame: "In partita",
	comingSoon: "In arrivo...",
	createTournament: "Crea torneo",
	name: "Nome del torneo",
	tournamentError: "Non può essere vuoto",
	tournamentPlayers: "Numero di giocatori",
	selectError: "Seleziona un numero",
	creator: "Creatore",
	kick: "Espelli",
	startTournament: "Inizia torneo",
	searchPlayers: "Ricerca giocatori",
	search: "Cerca",
	viewProfile: "Visualizza Profilo",
	leaderboardEmpty: "Classifica non disponibile",
	noMatches: "Nessuna partita giocata",
	noFriends: "Nessun amico per ora",
	noRequests: "Nessuna richiesta di amicizia in arrivo",
	noSentRequests: "Nessuna richiesta di amicizia inviata",
	noPlayers: "Nessun giocatore trovato",
	yes: "Sì",
	no: "No",
	tris: "Tris",
	playPong: "Gioca a Pong",
	playTris: "Gioca a Tris",
	loginSecond: "Accedi secondo giocatore",
	id: "ID univoco",
	editProfile: "Modifica Profilo",
	errorModalEmail: "Errore email",
	errorModalPass: "Errore password",
	emailInUse: "Questa email è già in uso. Scegline un'altra.",
	points: "Punti",
	firstRound: "Primo Turno",
	secondRound: "Secondo Turno",
	thirdRound: "Terzo Turno",
	fourthRound: "Quarto Turno",
	startNextMatch: "Inizia la Prossima Partita",
	startNextRound: "Inizia il Prossimo Turno",
	pointDiff: "Differenza Punti",
	passModal: "La password non è valida: ",
	},
	es: {
	home: "Inicio",
	language: "Idioma",
	play: "Jugar",
	leaderboard: "Clasificación",
	stats: "Estadísticas",
	profile: "Perfil",
	login: "Iniciar sesión",
	register: "Registrarse",
	login42: "Iniciar sesión con 42",
	signup42: "Registrarse con 42",
	logout: "Cerrar sesión",
	localMatch: "Jugar local",
	onlineMatch: "Jugar en línea",
	botMatch: "Jugar contra bot",
	tournament: "Torneo",
	back: "Atrás",
	pause: "Pausa",
	resume: "Reanudar",
	restart: "Reiniciar",
	sendFriend: "Enviar solicitud de amistad",
	quit: "Salir",
	quitMessage: "¿Estás seguro de que quieres salir?",
	footer: "Desarrollado por fracerba, ncortigi, everonel, lgaibazz",
	email: "Correo electrónico",
	username: "Nombre de usuario",
	password: "Contraseña",
	oldPassword: "Contraseña actual",
	newPassword: "Nueva contraseña",
	submit: "Enviar",
	emailHelp: "Introduzca una dirección de correo electrónico válida",
	userHelp: "Máximo 10 caracteres alfanuméricos",
	passHelp: "La contraseña debe tener al menos 8 caracteres, una letra mayúscula y un número",
	oldPasswordHelp: "Introduce tu contraseña actual",
	newPasswordHelp: "Introduce tu nueva contraseña o déjala en blanco",
	emailError: "Correo electrónico no válido",
	passError: "Contraseña incorrecta",
	oldPassError: "Contraseña actual incorrecta",
	player: "Jugador",
	games: "Partidas",
	wins: "Victorias",
	losses: "Derrotas",
	winrate: "Porcentaje de victorias",
	tournamentWon: "Torneos ganados",
	uploadImage: "Subir imagen",
	info: "Información",
	edit: "Editar",
	save: "Guardar",
	recentGames: "Partidas recientes",
	viewStats: "Estadísticas completas",
	friends: "Amigos",
	friendRequests: "Solicitudes de amistad",
	accept: "Aceptar",
	reject: "Rechazar",
	sentRequests: "Solicitudes enviadas",
	generalStats: "Estadísticas generales",
	modeResults: "Resultados por modo",
	localGames: "Partidas locales",
	botGames: "Partidas contra bot",
	tournamentGames: "Partidas de torneo",
	win: "Victoria",
	loss: "Derrota",
	local: "Local",
	online: "En línea",
	bot: "Bot",
	ingame: "En juego",
	comingSoon: "Próximamente...",
	createTournament: "Crear torneo",
	name: "Nombre del torneo",
	tournamentError: "No puede estar en blanco",
	tournamentPlayers: "Número de jugadores",
	selectError: "Selecciona un número",
	creator: "Creador",
	kick: "Expulsar",
	startTournament: "Comenzar torneo",
	searchPlayers: "Buscar jugadores",
	search: "Buscar",
	viewProfile: "Ver perfil",
	leaderboardEmpty: "Clasificación no disponible",
	noMatches: "No hay partidas jugadas",
	noFriends: "Aún no tienes amigos",
	noRequests: "No hay solicitudes de amistad entrantes",
	noSentRequests: "No hay solicitudes de amistad enviadas",
	noPlayers: "No se encontraron jugadores",
	yes: "Sí",
	no: "No",
	tris: "Tres en línea",
	playPong: "Jugar a Pong",
	playTris: "Jugar a Tres en línea",
	loginSecond: "Iniciar sesión segundo jugador",
	id: "ID único",
	editProfile: "Editar perfil",
	errorModalEmail: "Error de correo electrónico",
	errorModalPass: "Error de contraseña",
	emailInUse: "Este correo electrónico ya está en uso. Por favor, elige otro.",
	points: "Puntos",
	firstRound: "Primera Ronda",
	secondRound: "Segunda Ronda",
	thirdRound: "Tercera Ronda",
	fourthRound: "Cuarta Ronda",
	startNextMatch: "Comenzar la siguiente partida",
	startNextRound: "Comenzar la siguiente ronda",
	pointDiff: "Diferencia de puntos",
	passModal: "La contraseña no es válida: ",
	},
};

const translationsGame = {
	en: {
		tournamentWinner: " has won the tournament!",
		gameWinner: " has won the game!",
		you: "You",
		won: "Won!",
		lost: "Lost!",
		opponent: "Opponent",
		draw: "Draw!",
		wins: "Wins:",
		draws: "Draws:",
		time: "Time:",
		turn: "\'s Turn",
		passUser: "The password is too similar to the username",
		passEmail: "The password is too similar to the email",
		passCommon: "This password is too common",
	},
	it: {
		tournamentWinner: " ha vinto il torneo!",
		gameWinner: " ha vinto la partita!",
		you: "Hai",
		won: "Vinto!",
		lost: "Perso!",
		opponent: "Avversario",
		draw: "Pareggio!",
		wins: "Vittorie:",
		draws: "Pareggi:",
		time: "Tempo:",
		turn: "Turno di ",
		passUser: "La password è troppo simile al nome utente",
		passEmail: "La password è troppo simile all'email",
		passCommon: "Questa password è troppo comune",
	},
	es: {
		tournamentWinner: " ha ganado el torneo!",
		gameWinner: " ha ganado el juego!",
		you: "Tú",
		won: "Ganaste!",
		lost: "Perdiste!",
		opponent: "Oponente",
		draw: "Empate!",
		wins: "Victorias:",
		draws: "Empates:",
		time: "Tiempo:",
		turn: "Turno de ",
		passUser: "La contraseña es demasiado similar al nombre de usuario",
		passEmail: "La contraseña es demasiado similar al correo electrónico",
		passCommon: "Esta contraseña es demasiado común",
	},
}; 

const translationsCache = {};
const translationsGameCache = {};

export function updateLanguage(lang) {
	if (!translationsCache[lang]) {
		translationsCache[lang] = translations[lang];
	}
	const currentTranslations = translationsCache[lang];
	document.querySelectorAll('[data-translate]').forEach(element => {
		const key = element.getAttribute('data-translate');
		if (currentTranslations && currentTranslations[key]) {
			element.textContent = currentTranslations[key];
		}
	});
}

export function getTranslation(key, lang) {
	if (!translationsGameCache[lang]) {
		translationsGameCache[lang] = translationsGame[lang];
	}
	const currentTranslations = translationsGameCache[lang];
	if (currentTranslations && currentTranslations[key]) {
		return currentTranslations[key];
	}
	return key;
}
